[nvim]
targets = [
    { src = "~/.config/nvim", dir = "config" },
]

[starship]
targets = [
    { src = "~/.config/starship.toml" },
]

[wezterm]
targets = [
    { src = "~/.wezterm.lua" },
]

[ghostty]
targets = [
    { src = "~/Library/Application Support/com.mitchellh.ghostty/config" },
]

[fish]
targets = [
    { src = "~/.config/fish/config.fish" },
]

[vscode]
targets = [
    { src = "~/Library/Application Support/Code/User/settings.json" },
    { src = "~/Library/Application Support/Code/User/keybindings.json" },
    { src = "~/Library/Application Support/Code/User/snippets" },
]

[emacs]
targets = [
    { src = "~/.config/doom" }
]
