[nvim]
targets = [
    { src = "~/.config/nvim", dir = "config" },
]

[starship]
targets = [
    { src = "~/.config/starship.toml" },
]

[wezterm]
targets = [
    { src = "~/.wezterm.lua" },
]

[fish]
targets = [
    { src = "~/.config/fish/config.fish" }
]
